version: "3"
services:
  app:
    image: hkim0331/duct:0.1.0
    user: vscode
    volumes:
      - .:/usr/src/app
      # docker desktop, slow volume mount?
      # no. docker desktop itself is slow to make uberjar.
      # from when? v4.24.2
      - m2:/home/vscode/.m2
    working_dir: /usr/src/app
    entrypoint:
      - sleep
      - infinity

  db:
    image: postgres:14.9
    environment:
      POSTGRES_DB: qa
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_INITDB_ARGS: --encoding=UTF-8 --locale=C
      TZ: Asia/Toky
    volumes:
      - data:/var/lib/postgresql/data

volumes:
  m2:
    external: true
  data:
    driver: local
