services:
  qa:
    image: hkim0331/qa:0.3.0
    # user: vscode
    volumes:
      - .:/usr/src/app
      # docker desktop, slow volume mount?
      # no. docker desktop itself is slow to make uberjar.
      # from when? v4.24.2
      - m2:/root/.m2
    working_dir: /usr/src/app
    environment:
      QA_DEV: true
    entrypoint:
      - sleep
      - infinity

  db:
    image: postgres:14.11
    environment:
      POSTGRES_DB: qa
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_INITDB_ARGS: --encoding=UTF-8 --locale=C
      TZ: Asia/Toky
    volumes:
      - data:/var/lib/postgresql/data

volumes:
  m2:
    external: true
  data:
    driver: local
